# Generated by Django 6.1.1 on 2026-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='email_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='email_send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
