# Generated by Django 6.1.1 on 2026-09-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
