# Generated by Django 6.1.1 on 2026-09-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskactivity_deleted_at_taskactivity_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='taskactivity',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('due_date_changed', 'Due Date Changed'), ('deleted', 'Deleted'), ('restored', 'Restored')], max_length=30),
        ),
    ]
