# Generated by Django 6.1.1 on 2026-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
